#!/usr/bin/env bash

if [ -d "/home/esta/Software/miniforge3/bin/" ]; then
    source /home/esta/Software/miniforge3/bin/activate env_jupyter_aug24
fi

if [ -d "/home/ab/Software/miniforge3/bin/" ]; then
    source /home/ab/Software/miniforge3/bin/activate env_jupyter_sep24
fi

jupyter -h
jupyter lab
