; =========================
; Global colors (optional but clean)
; =========================
[colors]
background = #000000
background-inactive = #090909
foreground = #f3f4f5
foreground-inactive = #676E7D
urgent = #6a6a6a

; =========================
; DisplayPort bottom bar
; =========================
[bar/dp-bottom]
monitor = DisplayPort-2
bottom = true
width = 100%
height = 26

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = Source Code Pro:size=13

modules-left = i3
modules-right = time-dual

tray-position = none
padding-left = 2
padding-right = 2

; =========================
; HDMI top bar
; =========================
[bar/hdmi-top]
monitor = HDMI-A-0
bottom = false
width = 100%
height = 26

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = Source Code Pro:size=13

modules-right = chip-temp
tray-position = none

padding-left = 2
padding-right = 2

; =========================
; HDMI bot bar
; =========================
[bar/hdmi-bot]
monitor = HDMI-A-0
bottom = true
width = 100%
height = 26

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = Source Code Pro:size=13

modules-left = i3
modules-right = time-mono

tray-position = right
tray-padding = 2

padding-left = 2
padding-right = 2



; =========================
; i3 workspaces
; =========================
[module/i3]
type = internal/i3
pin-workspaces = true
index-sort = true
enable-click = true
enable-scroll = false

label-focused = %name%
label-focused-foreground = ${colors.foreground}
label-focused-padding = 0

label-unfocused = %name%
label-unfocused-foreground = ${colors.foreground-inactive}
label-unfocused-padding = 0

label-visible = %name%
label-visible-foreground = ${colors.foreground-inactive}
label-visible-padding = 0

label-urgent = %name%
label-urgent-foreground = ${colors.urgent}
label-urgent-padding = 0

label-separator = "|"
label-separator-foreground = ${colors.foreground-inactive}
label-separator-padding = 0

; =========================
; Time (current + India)
; =========================
[module/time-dual]
type = custom/script
interval = 1
exec = bash -c 'echo "$(date "+%a, %d-%b-%Y %H:%M:%S") | IND $(TZ="Asia/Kolkata" date "+%a, %d-%b %H:%M")"'

; =========================
; Time (current)
; =========================
[module/time-mono]
type = custom/script
interval = 1
exec = bash -c 'echo "$(date "+%a, %d-%b-%Y %H:%M:%S")"'

; =========================
; CPU / chip temperature
; =========================
[module/chip-temp]
type = custom/script
exec = ~/Software/esta_base/configs/sys-info.py
interval = 5

